name: Deploy Frontend to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Copy project files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "."   # Dockerfile + project sab kuch copy karega
        target: "/var/www/frontend-action/"

    - name: Run Docker on EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /var/www/frontend-action

          # Purane container ko hatao (agar chal raha hai)
          docker rm -f frontend-feedback || true

          # Purani image hatao (agar hai)
          docker rmi -f frontend-action || true

          # Nayi image build karo
          docker build -t frontend-action .

          # Naya container run karo
          docker run -d -p 3000:3000 --name frontend-feedback frontend-action

